// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Source: MLB Stats API (statsapi.mlb.com) (/api/v1/draft/2024).
// Copyright 2026 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt
// Resolved as of 2026-08-31. Draft facts+bio from the draft feed; current level/org/affiliate from people+teams; highestLevelReached from MiLB history (leagueListId=milb_all) + MLB debut. Status is heuristic (life-cycle only; trades are org-derived). Personal/non-commercial use (plan 0001, R1).
import type { DraftClass } from "../types";

export const guardians2024: DraftClass = {
  "team": "CLE",
  "year": 2024,
  "asOf": "2026-08-31",
  "entries": [
    {
      "pick": {
        "id": "draft-2024-1",
        "playerId": "683953",
        "draftYear": 2024,
        "round": "1",
        "pickNumber": 1,
        "draftingOrganizationId": "CLE",
        "school": "Oregon State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 8950000
      },
      "player": {
        "id": "683953",
        "mlbamId": 683953,
        "firstName": "Travis",
        "lastName": "Bazzana",
        "position": "2B",
        "birthDate": "2002-08-28",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Cleveland Guardians",
        "currentLevel": "MLB",
        "highestLevelReached": "MLB",
        "status": "MLB",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          },
          {
            "type": "MLB_DEBUT",
            "occurredAt": "2026-04-28"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-36",
        "playerId": "815785",
        "draftYear": 2024,
        "round": "CB-A",
        "pickNumber": 36,
        "draftingOrganizationId": "CLE",
        "school": "Chaparral HS",
        "schoolType": "HIGH_SCHOOL",
        "signed": true,
        "signingBonus": 2569200
      },
      "player": {
        "id": "815785",
        "mlbamId": 815785,
        "firstName": "Braylon",
        "lastName": "Doughty",
        "position": "P",
        "birthDate": "2005-12-07",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-48",
        "playerId": "695524",
        "draftYear": 2024,
        "round": "2",
        "pickNumber": 48,
        "draftingOrganizationId": "CLE",
        "school": "NC State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 2050000
      },
      "player": {
        "id": "695524",
        "mlbamId": 695524,
        "firstName": "Jacob",
        "lastName": "Cozart",
        "position": "C",
        "birthDate": "2003-01-09",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "LAA",
        "currentAffiliateName": "Rocket City Trash Pandas",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-84",
        "playerId": "815841",
        "draftYear": 2024,
        "round": "3",
        "pickNumber": 84,
        "draftingOrganizationId": "CLE",
        "school": "Gonzaga",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 2000000
      },
      "player": {
        "id": "815841",
        "mlbamId": 815841,
        "firstName": "Joseph",
        "lastName": "Oakie",
        "position": "P",
        "birthDate": "2006-05-09",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "HIGH_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-113",
        "playerId": "701178",
        "draftYear": 2024,
        "round": "4",
        "pickNumber": 113,
        "draftingOrganizationId": "CLE",
        "school": "Miami",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 446900
      },
      "player": {
        "id": "701178",
        "mlbamId": 701178,
        "firstName": "Rafe",
        "lastName": "Schlesinger",
        "position": "P",
        "birthDate": "2003-01-22",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-146",
        "playerId": "802146",
        "draftYear": 2024,
        "round": "5",
        "pickNumber": 146,
        "draftingOrganizationId": "CLE",
        "school": "West Virginia",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 425000
      },
      "player": {
        "id": "802146",
        "mlbamId": 802146,
        "firstName": "Aidan",
        "lastName": "Major",
        "position": "P",
        "birthDate": "2003-05-22",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "HIGH_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-175",
        "playerId": "801129",
        "draftYear": 2024,
        "round": "6",
        "pickNumber": 175,
        "draftingOrganizationId": "CLE",
        "school": "Wichita State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 75000
      },
      "player": {
        "id": "801129",
        "mlbamId": 801129,
        "firstName": "Caden",
        "lastName": "Favors",
        "position": "P",
        "birthDate": "2001-08-29",
        "bats": "R",
        "throws": "L",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-205",
        "playerId": "824029",
        "draftYear": 2024,
        "round": "7",
        "pickNumber": 205,
        "draftingOrganizationId": "CLE",
        "school": "Mt. Vernon HS",
        "schoolType": "HIGH_SCHOOL",
        "signed": true,
        "signingBonus": 525000
      },
      "player": {
        "id": "824029",
        "mlbamId": 824029,
        "firstName": "Cameron",
        "lastName": "Sullivan",
        "position": "P",
        "birthDate": "2006-03-22",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "ACL Guardians",
        "currentLevel": "COMPLEX",
        "highestLevelReached": "COMPLEX",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-235",
        "playerId": "805124",
        "draftYear": 2024,
        "round": "8",
        "pickNumber": 235,
        "draftingOrganizationId": "CLE",
        "school": "Rutgers",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 200000
      },
      "player": {
        "id": "805124",
        "mlbamId": 805124,
        "firstName": "Donovan",
        "lastName": "Zsak",
        "position": "P",
        "birthDate": "2003-07-12",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "HIGH_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-265",
        "playerId": "822483",
        "draftYear": 2024,
        "round": "9",
        "pickNumber": 265,
        "draftingOrganizationId": "CLE",
        "school": "Harvard",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 175000
      },
      "player": {
        "id": "822483",
        "mlbamId": 822483,
        "firstName": "Sean",
        "lastName": "Matson",
        "position": "P",
        "birthDate": "2002-06-02",
        "bats": "S",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-295",
        "playerId": "813949",
        "draftYear": 2024,
        "round": "10",
        "pickNumber": 295,
        "draftingOrganizationId": "CLE",
        "school": "Durant HS",
        "schoolType": "HIGH_SCHOOL",
        "signed": true,
        "signingBonus": 1800000
      },
      "player": {
        "id": "813949",
        "mlbamId": 813949,
        "firstName": "Chase",
        "lastName": "Mobley",
        "position": "P",
        "birthDate": "2006-06-05",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "ACL Guardians",
        "currentLevel": "COMPLEX",
        "highestLevelReached": "LOW_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-325",
        "playerId": "827628",
        "draftYear": 2024,
        "round": "11",
        "pickNumber": 325,
        "draftingOrganizationId": "CLE",
        "school": "Samford University",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "827628",
        "mlbamId": 827628,
        "firstName": "Garrett",
        "lastName": "Howe",
        "position": "2B",
        "birthDate": "2002-07-12",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "HIGH_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-355",
        "playerId": "692174",
        "draftYear": 2024,
        "round": "12",
        "pickNumber": 355,
        "draftingOrganizationId": "CLE",
        "school": "University of British Columbia",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "692174",
        "mlbamId": 692174,
        "firstName": "Sean",
        "lastName": "Heppner",
        "position": "P",
        "birthDate": "2002-09-14",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Hill City Howlers",
        "currentLevel": "LOW_A",
        "highestLevelReached": "LOW_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-385",
        "playerId": "701750",
        "draftYear": 2024,
        "round": "13",
        "pickNumber": 385,
        "draftingOrganizationId": "CLE",
        "school": "Oregon",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "701750",
        "mlbamId": 701750,
        "firstName": "Bennett",
        "lastName": "Thompson",
        "position": "C",
        "birthDate": "2002-12-16",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-415",
        "playerId": "825761",
        "draftYear": 2024,
        "round": "14",
        "pickNumber": 415,
        "draftingOrganizationId": "CLE",
        "school": "Saint Joseph's",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "825761",
        "mlbamId": 825761,
        "firstName": "Ryan",
        "lastName": "Cesarini",
        "position": "OF",
        "birthDate": "2002-12-16",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-445",
        "playerId": "701422",
        "draftYear": 2024,
        "round": "15",
        "pickNumber": 445,
        "draftingOrganizationId": "CLE",
        "school": "Florida State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "701422",
        "mlbamId": 701422,
        "firstName": "Conner",
        "lastName": "Whittaker",
        "position": "P",
        "birthDate": "2003-06-30",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "HIGH_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-475",
        "playerId": "825757",
        "draftYear": 2024,
        "round": "16",
        "pickNumber": 475,
        "draftingOrganizationId": "CLE",
        "school": "Maryknoll HS",
        "schoolType": "HIGH_SCHOOL",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "825757",
        "mlbamId": 825757,
        "firstName": "Jacob",
        "lastName": "Remily",
        "position": "P",
        "birthDate": "2006-05-08",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "ACL Guardians",
        "currentLevel": "COMPLEX",
        "highestLevelReached": "COMPLEX",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-505",
        "playerId": "695661",
        "draftYear": 2024,
        "round": "17",
        "pickNumber": 505,
        "draftingOrganizationId": "CLE",
        "school": "Georgia Tech",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "695661",
        "mlbamId": 695661,
        "firstName": "Logan",
        "lastName": "McGuire",
        "position": "P",
        "birthDate": "2002-09-12",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-535",
        "playerId": "801555",
        "draftYear": 2024,
        "round": "18",
        "pickNumber": 535,
        "draftingOrganizationId": "CLE",
        "school": "Puerto Rico Baseball Academy",
        "schoolType": "OTHER",
        "signed": true,
        "signingBonus": 25000
      },
      "player": {
        "id": "801555",
        "mlbamId": 801555,
        "firstName": "Izaak",
        "lastName": "Martinez",
        "position": "P",
        "birthDate": "2001-09-12",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-565",
        "playerId": "807575",
        "draftYear": 2024,
        "round": "19",
        "pickNumber": 565,
        "draftingOrganizationId": "CLE",
        "school": "Mississippi State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 55000
      },
      "player": {
        "id": "807575",
        "mlbamId": 807575,
        "firstName": "Cameron",
        "lastName": "Schuelke",
        "position": "P",
        "birthDate": "2002-01-14",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lake County Captains",
        "currentLevel": "HIGH_A",
        "highestLevelReached": "HIGH_A",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2024-595",
        "playerId": "808754",
        "draftYear": 2024,
        "round": "20",
        "pickNumber": 595,
        "draftingOrganizationId": "CLE",
        "school": "Arizona",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 50000
      },
      "player": {
        "id": "808754",
        "mlbamId": 808754,
        "firstName": "Cameron",
        "lastName": "Walty",
        "position": "P",
        "birthDate": "2002-05-14",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2024-07-14"
          }
        ]
      }
    }
  ]
};
