// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Source: MLB Stats API (statsapi.mlb.com) (/api/v1/draft/2021).
// Copyright 2026 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt
// Resolved as of 2026-08-31. Draft facts+bio from the draft feed; current level/org/affiliate from people+teams; highestLevelReached from MiLB history (leagueListId=milb_all) + MLB debut. Status is heuristic (life-cycle only; trades are org-derived). Personal/non-commercial use (plan 0001, R1).
import type { DraftClass } from "../types";

export const guardians2021: DraftClass = {
  "team": "CLE",
  "year": 2021,
  "asOf": "2026-08-31",
  "entries": [
    {
      "pick": {
        "id": "draft-2021-23",
        "playerId": "668909",
        "draftYear": 2021,
        "round": "1",
        "pickNumber": 23,
        "draftingOrganizationId": "CLE",
        "school": "East Carolina",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 2250000
      },
      "player": {
        "id": "668909",
        "mlbamId": 668909,
        "firstName": "Gavin",
        "lastName": "Williams",
        "position": "P",
        "birthDate": "1999-07-26",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Cleveland Guardians",
        "currentLevel": "MLB",
        "highestLevelReached": "MLB",
        "status": "MLB",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          },
          {
            "type": "MLB_DEBUT",
            "occurredAt": "2023-06-21"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-58",
        "playerId": "680951",
        "draftYear": 2021,
        "round": "2",
        "pickNumber": 58,
        "draftingOrganizationId": "CLE",
        "school": "Ole Miss",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 1200000
      },
      "player": {
        "id": "680951",
        "mlbamId": 680951,
        "firstName": "Douglas",
        "lastName": "Nikhazy",
        "position": "P",
        "birthDate": "1999-08-11",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "CHC",
        "currentAffiliateName": "ACL Cubs",
        "currentLevel": "COMPLEX",
        "highestLevelReached": "MLB",
        "status": "MLB",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          },
          {
            "type": "MLB_DEBUT",
            "occurredAt": "2025-04-26"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-69",
        "playerId": "676390",
        "draftYear": 2021,
        "round": "CB-B",
        "pickNumber": 69,
        "draftingOrganizationId": "CLE",
        "school": "Florida",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 1100000
      },
      "player": {
        "id": "676390",
        "mlbamId": 676390,
        "firstName": "Thomas",
        "lastName": "Mace",
        "position": "P",
        "birthDate": "1998-11-11",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-95",
        "playerId": "695780",
        "draftYear": 2021,
        "round": "3",
        "pickNumber": 95,
        "draftingOrganizationId": "CLE",
        "school": "Lakeland Christian School",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 850000
      },
      "player": {
        "id": "695780",
        "mlbamId": 695780,
        "firstName": "Jacob",
        "lastName": "Fox",
        "position": "1B",
        "birthDate": "2003-02-12",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-125",
        "playerId": "669067",
        "draftYear": 2021,
        "round": "4",
        "pickNumber": 125,
        "draftingOrganizationId": "CLE",
        "school": "Georgia",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 400000
      },
      "player": {
        "id": "669067",
        "mlbamId": 669067,
        "firstName": "Ryan",
        "lastName": "Webb",
        "position": "P",
        "birthDate": "1999-04-19",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-156",
        "playerId": "676440",
        "draftYear": 2021,
        "round": "5",
        "pickNumber": 156,
        "draftingOrganizationId": "CLE",
        "school": "Cal State Fullerton",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 259400
      },
      "player": {
        "id": "676440",
        "mlbamId": 676440,
        "firstName": "Tanner",
        "lastName": "Bibee",
        "position": "P",
        "birthDate": "1999-03-05",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Cleveland Guardians",
        "currentLevel": "MLB",
        "highestLevelReached": "MLB",
        "status": "MLB",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          },
          {
            "type": "MLB_DEBUT",
            "occurredAt": "2023-04-26"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-186",
        "playerId": "702126",
        "draftYear": 2021,
        "round": "6",
        "pickNumber": 186,
        "draftingOrganizationId": "CLE",
        "school": "Hawaii",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 450000
      },
      "player": {
        "id": "702126",
        "mlbamId": 702126,
        "firstName": "Aaron",
        "lastName": "Davenport",
        "position": "P",
        "birthDate": "2000-07-25",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-216",
        "playerId": "676393",
        "draftYear": 2021,
        "round": "7",
        "pickNumber": 216,
        "draftingOrganizationId": "CLE",
        "school": "Florida",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 167000
      },
      "player": {
        "id": "676393",
        "mlbamId": 676393,
        "firstName": "Jack",
        "lastName": "Leftwich",
        "position": "P",
        "birthDate": "1998-09-26",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-246",
        "playerId": "674868",
        "draftYear": 2021,
        "round": "8",
        "pickNumber": 246,
        "draftingOrganizationId": "CLE",
        "school": "UC Santa Barbara",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 167000
      },
      "player": {
        "id": "674868",
        "mlbamId": 674868,
        "firstName": "Rodney",
        "lastName": "Boone",
        "position": "P",
        "birthDate": "2000-04-09",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-276",
        "playerId": "702021",
        "draftYear": 2021,
        "round": "9",
        "pickNumber": 276,
        "draftingOrganizationId": "CLE",
        "school": "McNeese State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 125000
      },
      "player": {
        "id": "702021",
        "mlbamId": 702021,
        "firstName": "William",
        "lastName": "Dion",
        "position": "P",
        "birthDate": "2000-04-17",
        "bats": "L",
        "throws": "L",
        "currentOrganizationId": "WSH",
        "currentAffiliateName": "Washington Nationals",
        "currentLevel": "MLB",
        "highestLevelReached": "MLB",
        "status": "MLB",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          },
          {
            "type": "MLB_DEBUT",
            "occurredAt": "2026-05-26"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-306",
        "playerId": "680916",
        "draftYear": 2021,
        "round": "10",
        "pickNumber": 306,
        "draftingOrganizationId": "CLE",
        "school": "Florida",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 175000
      },
      "player": {
        "id": "680916",
        "mlbamId": 680916,
        "firstName": "Franco",
        "lastName": "Aleman",
        "position": "P",
        "birthDate": "2000-06-26",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "MLB",
        "status": "MLB",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          },
          {
            "type": "MLB_DEBUT",
            "occurredAt": "2026-05-10"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-336",
        "playerId": "701533",
        "draftYear": 2021,
        "round": "11",
        "pickNumber": 336,
        "draftingOrganizationId": "CLE",
        "school": "Southern Mississippi",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 125000
      },
      "player": {
        "id": "701533",
        "mlbamId": 701533,
        "firstName": "Hunter",
        "lastName": "Stanley",
        "position": "P",
        "birthDate": "1997-11-25",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-366",
        "playerId": "701634",
        "draftYear": 2021,
        "round": "12",
        "pickNumber": 366,
        "draftingOrganizationId": "CLE",
        "school": "Long Beach State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 125000
      },
      "player": {
        "id": "701634",
        "mlbamId": 701634,
        "firstName": "Connor",
        "lastName": "Kokx",
        "position": "OF",
        "birthDate": "2000-02-24",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "RELEASED",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-396",
        "playerId": "681571",
        "draftYear": 2021,
        "round": "13",
        "pickNumber": 396,
        "draftingOrganizationId": "CLE",
        "school": "Clemson",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "681571",
        "mlbamId": 681571,
        "firstName": "Davis",
        "lastName": "Sharpe",
        "position": "P",
        "birthDate": "2000-01-30",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-426",
        "playerId": "671143",
        "draftYear": 2021,
        "round": "14",
        "pickNumber": 426,
        "draftingOrganizationId": "CLE",
        "school": "University of California - Irvine",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "671143",
        "mlbamId": 671143,
        "firstName": "Trenton",
        "lastName": "Denholm",
        "position": "P",
        "birthDate": "1999-11-29",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-456",
        "playerId": "685095",
        "draftYear": 2021,
        "round": "15",
        "pickNumber": 456,
        "draftingOrganizationId": "CLE",
        "school": "Coastal Carolina",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 125000
      },
      "player": {
        "id": "685095",
        "mlbamId": 685095,
        "firstName": "Alaska",
        "lastName": "Abney",
        "position": "P",
        "birthDate": "2000-05-05",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-486",
        "playerId": "679903",
        "draftYear": 2021,
        "round": "16",
        "pickNumber": 486,
        "draftingOrganizationId": "CLE",
        "school": "UCLA",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 75000
      },
      "player": {
        "id": "679903",
        "mlbamId": 679903,
        "firstName": "Zachary",
        "lastName": "Pettway",
        "position": "P",
        "birthDate": "1999-01-29",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Lynchburg Hillcats",
        "currentLevel": "LOW_A",
        "highestLevelReached": "LOW_A",
        "status": "RELEASED",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-516",
        "playerId": "696263",
        "draftYear": 2021,
        "round": "17",
        "pickNumber": 516,
        "draftingOrganizationId": "CLE",
        "school": "Arizona State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 50000
      },
      "player": {
        "id": "696263",
        "mlbamId": 696263,
        "firstName": "William",
        "lastName": "Thornton",
        "position": "P",
        "birthDate": "2000-07-08",
        "bats": "L",
        "throws": "R",
        "currentAffiliateName": "Caliente de Durango",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "INDEPENDENT",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-546",
        "playerId": "702269",
        "draftYear": 2021,
        "round": "18",
        "pickNumber": 546,
        "draftingOrganizationId": "CLE",
        "school": "Longwood HS",
        "schoolType": "HIGH_SCHOOL",
        "signed": true,
        "signingBonus": 150000
      },
      "player": {
        "id": "702269",
        "mlbamId": 702269,
        "firstName": "Thomas",
        "lastName": "Ventimiglia",
        "position": "P",
        "birthDate": "2003-10-01",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "ACL Guardians",
        "currentLevel": "COMPLEX",
        "highestLevelReached": "COMPLEX",
        "status": "RELEASED",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-576",
        "playerId": "694773",
        "draftYear": 2021,
        "round": "19",
        "pickNumber": 576,
        "draftingOrganizationId": "CLE",
        "school": "NC State",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 75000
      },
      "player": {
        "id": "694773",
        "mlbamId": 694773,
        "firstName": "Reid",
        "lastName": "Johnston",
        "position": "P",
        "birthDate": "1999-04-07",
        "bats": "L",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Akron RubberDucks",
        "currentLevel": "AA",
        "highestLevelReached": "AA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    },
    {
      "pick": {
        "id": "draft-2021-606",
        "playerId": "681313",
        "draftYear": 2021,
        "round": "20",
        "pickNumber": 606,
        "draftingOrganizationId": "CLE",
        "school": "University of San Diego",
        "schoolType": "COLLEGE",
        "signed": true,
        "signingBonus": 300000
      },
      "player": {
        "id": "681313",
        "mlbamId": 681313,
        "firstName": "Jake",
        "lastName": "Miller",
        "position": "P",
        "birthDate": "2000-07-14",
        "bats": "R",
        "throws": "R",
        "currentOrganizationId": "CLE",
        "currentAffiliateName": "Columbus Clippers",
        "currentLevel": "AAA",
        "highestLevelReached": "AAA",
        "status": "ACTIVE",
        "milestones": [
          {
            "type": "DRAFTED",
            "occurredAt": "2021-07-11"
          }
        ]
      }
    }
  ]
};
