// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Static M1 seed — real Cleveland draft classes from the MLB Stats API.
import type { DraftClass } from "../types";
import { guardians2021 } from "./guardians-2021";
import { guardians2024 } from "./guardians-2024";

export { organizations, organizationsById } from "./organizations";
export { guardians2021 } from "./guardians-2021";
export { guardians2024 } from "./guardians-2024";

export const draftClasses: DraftClass[] = [guardians2021, guardians2024];

export const PROVENANCE = {
  source: "MLB Stats API (statsapi.mlb.com)",
  copyright: "Copyright 2026 MLB Advanced Media, L.P.  Use of any content on this page acknowledges agreement to the terms posted here http://gdx.mlb.com/components/copyright.txt",
} as const;
