// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
import type { Organization } from "../types";

export const organizations: Organization[] = [
  {
    "id": "CLE",
    "mlbamId": 114,
    "name": "Cleveland Guardians",
    "abbreviation": "CLE"
  },
  {
    "id": "CHC",
    "mlbamId": 112,
    "name": "Chicago Cubs",
    "abbreviation": "CHC"
  },
  {
    "id": "LAA",
    "mlbamId": 108,
    "name": "Los Angeles Angels",
    "abbreviation": "LAA"
  },
  {
    "id": "WSH",
    "mlbamId": 120,
    "name": "Washington Nationals",
    "abbreviation": "WSH"
  }
];

export const organizationsById: Record<string, Organization> = Object.fromEntries(
  organizations.map((o) => [o.id, o]),
);
