// Deterministic, offline generator: every data/raw/guardians-<year>.json ->
// the typed seed modules under src/lib/baseball/seed/. Re-run with
// `node scripts/generate-seed.mjs` after refreshing the raw files. The emitted
// string literals are type-checked against the domain unions by `tsc`, so bad
// data fails the build rather than reaching the UI.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const RAW_DIR = path.join(here, "../data/raw");
const SEED_DIR = path.join(here, "../src/lib/baseball/seed");

// MLB draft opening dates by year (milestones-lite uses the class's draft date).
const DRAFT_START = { 2021: "2021-07-11", 2024: "2024-07-14" };
const draftDate = (year) => DRAFT_START[year] ?? `${year}-07-15`;

function schoolType(school) {
  if (!school) return undefined;
  if (/\bHS\b|High School/i.test(school)) return "HIGH_SCHOOL";
  if (/Academy/i.test(school)) return "OTHER";
  return "COLLEGE";
}

function milestones(pk, year) {
  const ms = [{ type: "DRAFTED", occurredAt: draftDate(year) }];
  // Debut org is not asserted here (may differ from current org after a trade).
  if (pk.mlbDebutDate) ms.push({ type: "MLB_DEBUT", occurredAt: pk.mlbDebutDate });
  return ms;
}

function entryFrom(pk, year) {
  const player = {
    id: String(pk.mlbamId),
    mlbamId: pk.mlbamId,
    firstName: pk.firstName,
    lastName: pk.lastName,
    position: pk.position,
    birthDate: pk.birthDate,
    bats: pk.bats,
    throws: pk.throws,
    currentOrganizationId: pk.currentOrganizationId ?? undefined,
    currentAffiliateName: pk.currentAffiliateName ?? undefined,
    currentLevel: pk.currentLevel,
    highestLevelReached: pk.highestLevelReached,
    status: pk.status,
    milestones: milestones(pk, year),
  };
  const pick = {
    id: `draft-${year}-${pk.pickNumber}`,
    playerId: player.id,
    draftYear: year,
    round: pk.round,
    pickNumber: pk.pickNumber,
    draftingOrganizationId: "CLE",
    school: pk.school,
    schoolType: schoolType(pk.school),
    signed: pk.signed,
    signingBonus: pk.signingBonus,
  };
  return { pick, player };
}

const lit = (v) => JSON.stringify(v, null, 2);
const varName = (year) => `guardians${year}`;

const rawFiles = fs
  .readdirSync(RAW_DIR)
  .filter((f) => /^guardians-\d{4}\.json$/.test(f))
  .sort();

fs.mkdirSync(SEED_DIR, { recursive: true });

const classes = [];
const orgById = new Map();
let copyright = "";

for (const file of rawFiles) {
  const raw = JSON.parse(fs.readFileSync(path.join(RAW_DIR, file), "utf8"));
  const year = Number(file.match(/(\d{4})/)[1]);
  copyright = raw._provenance.copyright;
  for (const o of raw.organizations) if (!orgById.has(o.id)) orgById.set(o.id, o);

  const draftClass = {
    team: "CLE",
    year,
    asOf: raw._provenance.statusResolvedAsOf,
    entries: raw.picks.map((pk) => entryFrom(pk, year)),
  };

  const out = `// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Source: ${raw._provenance.source} (${raw._provenance.draftEndpoint}).
// ${raw._provenance.copyright}
// Resolved as of ${raw._provenance.statusResolvedAsOf}. ${raw._provenance.note}
import type { DraftClass } from "../types";

export const ${varName(year)}: DraftClass = ${lit(draftClass)};
`;
  fs.writeFileSync(path.join(SEED_DIR, `guardians-${year}.ts`), out);
  classes.push({ year, name: varName(year) });
}

// Merged organizations (CLE first, then alpha).
const organizations = [...orgById.values()].sort((a, b) =>
  a.id === "CLE" ? -1 : b.id === "CLE" ? 1 : a.id.localeCompare(b.id),
);
fs.writeFileSync(
  path.join(SEED_DIR, "organizations.ts"),
  `// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
import type { Organization } from "../types";

export const organizations: Organization[] = ${lit(organizations)};

export const organizationsById: Record<string, Organization> = Object.fromEntries(
  organizations.map((o) => [o.id, o]),
);
`,
);

// Barrel: aggregate all classes + org lookups + shared provenance.
const imports = classes.map((c) => `import { ${c.name} } from "./guardians-${c.year}";`).join("\n");
fs.writeFileSync(
  path.join(SEED_DIR, "index.ts"),
  `// GENERATED by scripts/generate-seed.mjs — do not edit by hand.
// Static M1 seed — real Cleveland draft classes from the MLB Stats API.
import type { DraftClass } from "../types";
${imports}

export { organizations, organizationsById } from "./organizations";
${classes.map((c) => `export { ${c.name} } from "./guardians-${c.year}";`).join("\n")}

export const draftClasses: DraftClass[] = [${classes.map((c) => c.name).join(", ")}];

export const PROVENANCE = {
  source: "MLB Stats API (statsapi.mlb.com)",
  copyright: ${JSON.stringify(copyright)},
} as const;
`,
);

console.log(`generated ${classes.length} class file(s): ${classes.map((c) => c.year).join(", ")}`);
console.log(`organizations: ${organizations.map((o) => o.id).join(", ")}`);
